apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: microservices-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/elorm116/devops-production-microservices.git
    targetRevision: HEAD
    path: k8s/base   # ← adjust to your actual manifests folder (deployments/services/ingress)
  destination:
    server: https://kubernetes.default.svc
    namespace: default   # or your target ns
  syncPolicy:
    automated:
      prune: true
      selfHeal: true